backend:
  name: git-gateway
  branch: main  # Ensure this matches your GitHub default branch (main or master)

media_folder: "assets/uploads"  # Folder in your repo where uploads are stored
public_folder: "/assets/uploads"  # Public URL path to uploads

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
