backend:
  name: git-gateway
  branch: main # Change to your main branch name

media_folder: "assets/uploads" # Where images, etc. are stored
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
